### ISSUE TITLE
Things to be added to the wiki page

### ISSUE THREAD

**Issue by JonasVanHoof** [lblod/ember-submission-form-fields#153]
Hi there, I'm updating the [wiki pages](https://github.com/lblod/ember-submission-form-fields/wiki) of this addon (`ember-submission-form-fields`). The goal is clear I think  to give the developer that is using this the information that is needed to start using this addon. I already added some information about the addon but as I do not know everything about it  im shooting the question to the person reading this to let me know what is missing here.

Just add a comment below with the possible missing information in [the wiki](https://github.com/lblod/ember-submission-form-fields/wiki). If you cannot think about anything that is missing but have a nice way on how to structure github wiki's  please let me know as it does not feel ideal on how it's done right now :sweat_smile:

**Comment by aatauil** [comment]
I think it looks great! havent gone through it completely yet but expecting it to grow over time. Thanks for the efforts! We will keep track in jira instead of in the issues tab of github. Closing this issue. Thanks again! :rocket:
