### ISSUE TITLE
[Checkbox] checked + disabled

### ISSUE THREAD

**Issue by aatauil** [lblod/ember-submission-form-fields#67]
Low prio reminder: The checked state should be passed as an argument (checked -> @checked). @Windvis unless there is reason its done this way? Currently, because of this, when a checkbox is both checked + disabled it will only show the disabled state. This can cause some confusion/panic for the user

https://github.com/lblod/ember-submission-form-fields/blob/master/addon/components/rdf-input-fields/checkbox.hbs#L12
https://github.com/lblod/ember-submission-form-fields/blob/master/addon/components/rdf-input-fields/concept-scheme-multi-select-checkboxes.hbs#L26

**Comment by Windvis** [comment]
Good catch. It was like that when I "modernized" them, but I missed that state. I think the original idea was to bypass the 2-way-binding? I'm not sure if the change event will receive the correct value if both the event and 2-way-binding is used. Worth a try though.

**Comment by Windvis** [comment]
@aatauil I can't seem to reproduce it in the test app? If I check some checkboxes and then toggle the "read only" mode it looks like this:

![image](https://user-images.githubusercontent.com/3533236/163411679-4a786e1f-15bc-4989-bf2f-befd508509e6.png)

Which looks the same as the [Appuniversum version](https://appuniversum.github.io/ember-appuniversum/?path=/story/components-forms-aucheckbox--component&args=disabled:true;checked:true)?

Maybe I misunderstood what you meant.

**Comment by aatauil** [comment]
Did you reload the page? I just tested it on dev and it only happens on full reload. When you just send in a form and it changes to @show mode then it displays correctly surprisingly
see

**Comment by Windvis** [comment]
After discussing with @aatauil in chat, we came to the conclusing that it's the same issue as the `type="number"` issue: https://github.com/appuniversum/ember-appuniversum/issues/217

We should pass the value as an argument for now. Ideally AuControlCheckbox will use a native input element instead of the `<Input>` component.
